["Du temps que la Nature en sa verve puissante",
 "Concevait chaque jour des enfants monstrueux,",
 "J'eusse aimé vivre auprès d'une jeune géante,",
 "Comme aux pieds d'une reine un chat voluptueux.",
 "J'eusse aimé voir son corps fleurir avec son âme",
 "Et grandir librement dans ses terribles jeux;",
 "Deviner si son coeur couve une sombre flamme",
 "Aux humides brouillards qui nagent dans ses yeux;",
 "Parcourir à loisir ses magnifiques formes;",
 "Ramper sur le versant de ses genoux énormes,",
 "Et parfois en été, quand les soleils malsains,",
 "Lasse, la font s'étendre à travers la campagne,",
 "Dormir nonchalamment à l'ombre de ses seins,",
 "Comme un hameau paisible au pied d'une montagne."]

