{
   "french":      
        ["Du temps que la Nature en sa verve puissante",
         "Concevait chaque jour des enfants monstrueux,",
         "J'eusse aimé vivre auprès d'une jeune géante,",
         "Comme aux pieds d'une reine un chat voluptueux.",
         "J'eusse aimé voir son corps fleurir avec son âme",
         "Et grandir librement dans ses terribles jeux;",
         "Deviner si son coeur couve une sombre flamme",
         "Aux humides brouillards qui nagent dans ses yeux;",
         "Parcourir à loisir ses magnifiques formes;",
         "Ramper sur le versant de ses genoux énormes,",
         "Et parfois en été, quand les soleils malsains,",
         "Lasse, la font s'étendre à travers la campagne,",
         "Dormir nonchalamment à l'ombre de ses seins,",
         "Comme un hameau paisible au pied d'une montagne."],
    "english":
       ["In those times when Nature in powerful zest",
        "Conceived each day monstrous children,",
        "I would have loved to live near a young giantess,",
        "A voluptuous cat at the feet of a queen.",
        "I would have loved to see her body flower with her soul,",
        "To grow up freely in her prodigious play;",
        "To find if her heart bred some dark flame",
        "Amongst the humid mists swimming in her eyes;",
        "To run leisurely over her marvelous lines;",
        "To creep along the slopes of her enormous knees,",
        "And sometimes in summer, when impure suns",
        "Made her wearily stretch out across the countryside,",
        "To sleep carelessly in the shadow of her breasts, ",
        "Like a peaceful village at the foot of a mountain."],
    "spanish":
       ["Cuando Natura en su inspiración pujante",
        "Concebía cada día hijos monstruosos,",
        "Me hubiera placido vivir cerca de una joven giganta,",
        "Como a los pies de una reina un gato voluptuoso.",
        "Me hubiera agradado ver su cuerpo florecer con su alma",
        "Y crecer libremente en sus terribles juegos;",
        "Adivinar si su corazón cobija una sombría llama",
        "En las húmedas brumas que flotan en sus ojos;",
        "Recorrer a mi gusto sus magníficas formas;",
        "Arrastrarme en la pendiente de sus rodillas enormes,",
        "Y a veces, en estío, cuando los soles malsanos,",
        "Laxa, la hacen tenderse a través de la campiña,",
        "Dormir despreocupadamente a la sombra de sus senos,",
        "Como una plácida aldea al pie de una montaña."]
}
